query AllActivities($search: String) {
  activities(where: { _or: [{ notes: { _ilike: $search } }, { source: { _ilike: $search } }] }) {
    id
    type
    notes
    source
    created_by
    created_at
    updated_at
    created_by_object {
      id
      username
    }
  }
}
