#import './users.fragment.gql'

fragment ActivityFragment on activities {
  id
  type
  notes
  source
  created_by
  created_at
  updated_at
}

fragment CreatedByFragment on activities {
  created_by_object {
    ...MiniUserFragment
  }
}

fragment ActivityAssetsFragment on activities {
  activity_assets {
    asset {
      id
      name
    }
  }
}

fragment ActivityListFragment on activities {
  ...ActivityFragment
  ...CreatedByFragment
  ...ActivityAssetsFragment
}
