#import './activities.fragment.gql'

query AllActivities($search: String) {
  items: activities(
    where: {
      _or: [
        { notes: { _ilike: $search } }
        { source: { _ilike: $search } }
        #  { type: { _ilike: $search } } # Todo (Nour): can't filter on types
        { created_by_object: { username: { _ilike: $search } } }
        { activity_assets: { asset: { name: { _ilike: $search } } } }
      ]
    }
    order_by: { created_at: desc }
  ) {
    ...ActivityListFragment
  }
}
