#import './articles.fragment.gql'

query AllArticles($search: String) {
  items: articles(
    where: {
      _or: [
        { title: { _ilike: $search } }
        { summary: { _ilike: $search } }
        { body: { _ilike: $search } }
        #  { status: { _ilike: $search } } # Todo (Nour): can't filter on status
        { created_by_object: { username: { _ilike: $search } } }
      ]
    }
    order_by: { created_at: desc }
  ) {
    ...ArticleFragment
    ...CreatedByFragment
  }
}
