#import './users.fragment.gql'

fragment AssetMiniFragment on assets {
  id
  name
}

fragment AssetFragment on assets {
  ...AssetMiniFragment
  category
  description
  url
  created_by
  created_at
  updated_at
}

fragment AssetCreatedByFragment on assets {
      created_by_object {
      ...MiniUserFragment
    }
}

fragment AssetListFragment on assets {
  ...AssetFragment
  ...AssetCreatedByFragment
}