#import './assets.fragment.gql'

subscription StreamAssets($search: String!, $now: timestamptz) {
  # will get all the assets that have `created_at > now` in batches of 5 rows
  assets_stream(
    cursor: { initial_value: { created_at: $now }, ordering: ASC }
    batch_size: 5
    where: { _or: [{ name: { _ilike: $search } }, { description: { _ilike: $search } }, { url: { _ilike: $search } }] }
  ) {
    ...AssetFragment
  }
}
