query AllEnums {
  activity_type {
    value
    comment
  }
  asset_category {
    value
    comment
  }
  task_status {
    value
    comment
  }
  user_role {
    value
    comment
  }
  article_status {
    value
    comment
  }
  article_type {
    value
    comment
  }
}
