POST http://localhost:6000/auth/register
Content-Type: application/json

{
  "username": "mimi",
  "password": "password"
}
> {%
  client.log(response.body.token)
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

###
POST http://localhost:6000/auth/login
Content-Type: application/json

{
  "username": "mimi",
  "password": "password"
}
> {%
  client.log(response.body.token)
  client.test("Request executed successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
  });
%}

###
