POST http://localhost:6000/auth/register
Content-Type: application/json

{
  "username": "mimi",
  "password": "password"
}
###
POST http://localhost:6000/auth/login
Content-Type: application/json

{
  "username": "mimi",
  "password": "password"
}
###
