version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
    - db_data:/var/lib/postgresql/data
    env_file:
      - grid-database/.env
    ports:
      - "5432:5432"
  graphql-engine:
    image: hasura/graphql-engine:v2.18.0
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    restart: always
    env_file:
      - grid-database/.env
  ui:
    image: nourspace/grid-ui
    build: ./grid-ui
    ports:
    - "80:80"
    restart: always
    env_file:
      - grid-ui/.env
  # Todo (Nour): Add auth
  # Todo (Nour): Add console
volumes:
  db_data:

