version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - grid-database/.env.local
    volumes:
      - db_data:/var/lib/postgresql/data

  graphql-engine:
    image: hasura/graphql-engine:v2.18.0
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - grid-database/.env.local
    depends_on:
      - "postgres"

  # Todo (Nour): Add console service

  ui:
    image: nourspace/grid-ui
    build: ./grid-ui
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - grid-ui/.env.local

  auth:
    image: nourspace/grid-auth
    build: ./grid-auth
    restart: always
    ports:
      - "5050:5050"
    env_file:
      - grid-auth/.env.local

volumes:
  db_data:
