-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE TABLE activity_type (
--   value text PRIMARY KEY,
--   comment text
-- );
-- INSERT INTO activity_type (value, comment) VALUES
--   ('update', 'Observed an update on the asset'),
--   ('news', 'Read news article on the asset'),
--   ('post', 'Read blog post on the asset'),
--   ('video', 'Watched video about the asset'),
--   ('podcast', 'Heared podcast about the asset')
-- ;
